version: 2

sources:
  - name: sandbox
    schema: sanderson_dbt_airbnb_raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
                  config:
                    severity: warn
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
      - name: hosts
        identifier: raw_hosts
        # freshness:
        #   warn_after: {count: 6, period: day}
        #   error_after: {count: 9, period: day}